let a = `hello`;
let b = `owu`;
let c  = `com`;
let d = `ua`;
let f = 1;
let g = 10;
let h = -999;
let i = 123;
let j = 3.14;
let k = 2.7;
let l = 16;
let m = true;
let n = false;
console.log(a, b, c, d, f, g, h, i, j, k, l, m, n);